feat: add review mode custom variables
oat-sa/extension-tao-lti pull request #305
Opened 2021-09-21 14:21 UTC by emgolubev

Related to: https://oat-sa.atlassian.net/browse/TR-1910

see https://github.com/oat-sa/extension-lti-test-review/pull/87

2021-09-21 14:23 UTC, alexeyvy approved these changes

2021-09-23 12:24 UTC, wazelin requested changes

2021-09-23 12:24 UTC, wazelin commented on test/unit/models/classes/user/Lti1p3UserTest.php
> +include_once dirname(__FILE__) . '/../../../../../includes/raw_start.php';
```suggestion
include_once __DIR__ . '/../../../../../includes/raw_start.php';
```

2021-09-23 12:53 UTC, wazelin approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`

2021-09-23 12:56 UTC, merged