Guest user lti1p3 lang detection
oat-sa/extension-tao-lti pull request #365
Opened 2023-04-21 11:44 UTC by poyuki

# [REL-1101](https://oat-sa.atlassian.net/browse/REL-1101)

## Summary
This PR aim to provide lang detection for guest user and usage of `DEFAULT_ANONYMOUS_INTERFACE_LANG`.

I have some doubts about this solution.  From my point of view, it's a bit crutchy, but at the moment I couldn't find anything more suitable.

## How to test
- checkout branch
- update `DEFAULT_ANONYMOUS_INTERFACE_LANG`
- launch remote delivery on TAO 3.x
- defined locale should be used in Advance testrunner

2023-04-21 15:54 UTC, wazelin requested changes
Right. This does work quite well, but not exactly what I had in mind.

I believe the change should be done on the generis-user itself.

2023-04-21 15:58 UTC, poyuki commented
@wazelin I just moved in 0 breaking change direction

2023-04-21 16:00 UTC, wazelin commented
> @wazelin I just moved in 0 breaking change direction

Fair enough.
Let's return to this problem and options to its solution on Monday. Both options are viable IMO. We just have to understand better what the trade offs of each are.

2023-05-02 09:09 UTC, poyuki commented
closed in favor of https://github.com/oat-sa/generis/pull/1037

2024-02-15 16:57 UTC, wazelin approved these changes

2024-02-15 16:58 UTC, wazelin commented
Reviving the PR with a dependency on https://github.com/oat-sa/generis/pull/1106.

2024-04-03 12:39 UTC, closed without merging